import 'dart:io';
import 'package:flutter/foundation.dart';
import 'package:path_provider/path_provider.dart';
import 'package:share_plus/share_plus.dart';
import 'package:intl/intl.dart';
import '../../../features/transactions/data/models/transaction_model.dart';
import '../../../features/transactions/data/repositories/transaction_repository.dart';
import '../utils/currency_formatter.dart';

class ExportService {
  final TransactionRepository _repository;
  
  ExportService(this._repository);
  
  /// Export transactions to CSV format
  Future<String?> exportToCSV({
    DateTime? startDate,
    DateTime? endDate,
  }) async {
    try {
      final transactions = await _getTransactions(startDate, endDate);
      
      if (transactions.isEmpty) {
        return null;
      }
      
      // Build CSV content
      final buffer = StringBuffer();
      
      // Header
      buffer.writeln('Tanggal,Deskripsi,Kategori,Tipe,Jumlah,Mood');
      
      // Data rows
      for (final tx in transactions) {
        final date = DateFormat('yyyy-MM-dd HH:mm').format(tx.date);
        final description = _escapeCSV(tx.description);
        final category = tx.category.displayName;
        final type = tx.type.name == 'income' ? 'Pemasukan' : 'Pengeluaran';
        final amount = tx.amount.toStringAsFixed(0);
        final mood = tx.mood?.name ?? '-';
        
        buffer.writeln('$date,$description,$category,$type,$amount,$mood');
      }
      
      // Save file
      final fileName = 'rupia_export_${DateFormat('yyyyMMdd_HHmmss').format(DateTime.now())}.csv';
      final filePath = await _saveFile(fileName, buffer.toString());
      
      return filePath;
    } catch (e) {
      debugPrint('Export CSV error: $e');
      return null;
    }
  }
  
  /// Export transactions summary to text format
  Future<String?> exportSummary({
    DateTime? startDate,
    DateTime? endDate,
  }) async {
    try {
      final transactions = await _getTransactions(startDate, endDate);
      
      if (transactions.isEmpty) {
        return null;
      }
      
      // Calculate summary
      double totalIncome = 0;
      double totalExpense = 0;
      final categoryExpense = <String, double>{};
      
      for (final tx in transactions) {
        if (tx.type.name == 'income') {
          totalIncome += tx.amount;
        } else {
          totalExpense += tx.amount;
          final cat = tx.category.displayName;
          categoryExpense[cat] = (categoryExpense[cat] ?? 0) + tx.amount;
        }
      }
      
      // Build summary content
      final buffer = StringBuffer();
      final dateFormatter = DateFormat('dd MMM yyyy');
      
      buffer.writeln('═══════════════════════════════════════');
      buffer.writeln('        LAPORAN KEUANGAN RUPIA');
      buffer.writeln('═══════════════════════════════════════');
      buffer.writeln();
      
      if (startDate != null && endDate != null) {
        buffer.writeln('Periode: ${dateFormatter.format(startDate)} - ${dateFormatter.format(endDate)}');
      } else {
        buffer.writeln('Periode: Semua waktu');
      }
      buffer.writeln('Total Transaksi: ${transactions.length}');
      buffer.writeln();
      
      buffer.writeln('═══════════════════════════════════════');
      buffer.writeln('              RINGKASAN');
      buffer.writeln('═══════════════════════════════════════');
      buffer.writeln();
      buffer.writeln('Total Pemasukan  : ${CurrencyFormatter.format(totalIncome)}');
      buffer.writeln('Total Pengeluaran: ${CurrencyFormatter.format(totalExpense)}');
      buffer.writeln('───────────────────────────────────────');
      buffer.writeln('Saldo            : ${CurrencyFormatter.format(totalIncome - totalExpense)}');
      buffer.writeln();
      
      if (categoryExpense.isNotEmpty) {
        buffer.writeln('═══════════════════════════════════════');
        buffer.writeln('       PENGELUARAN PER KATEGORI');
        buffer.writeln('═══════════════════════════════════════');
        buffer.writeln();
        
        // Sort by amount descending
        final sorted = categoryExpense.entries.toList()
          ..sort((a, b) => b.value.compareTo(a.value));
        
        for (final entry in sorted) {
          final percentage = (entry.value / totalExpense * 100).toStringAsFixed(1);
          buffer.writeln('${entry.key.padRight(20)}: ${CurrencyFormatter.format(entry.value)} ($percentage%)');
        }
      }
      
      buffer.writeln();
      buffer.writeln('═══════════════════════════════════════');
      buffer.writeln('Generated by Rupia App');
      buffer.writeln(DateFormat('dd MMM yyyy HH:mm').format(DateTime.now()));
      buffer.writeln('═══════════════════════════════════════');
      
      // Save file
      final fileName = 'rupia_summary_${DateFormat('yyyyMMdd_HHmmss').format(DateTime.now())}.txt';
      final filePath = await _saveFile(fileName, buffer.toString());
      
      return filePath;
    } catch (e) {
      debugPrint('Export summary error: $e');
      return null;
    }
  }
  
  /// Share exported file
  Future<void> shareFile(String filePath) async {
    try {
      await Share.shareXFiles([XFile(filePath)]);
    } catch (e) {
      debugPrint('Share file error: $e');
    }
  }
  
  // Helper methods
  Future<List<TransactionModel>> _getTransactions(DateTime? startDate, DateTime? endDate) async {
    if (startDate != null && endDate != null) {
      return await _repository.getTransactionsByDateRange(startDate, endDate);
    }
    return await _repository.getAllTransactions();
  }
  
  String _escapeCSV(String value) {
    if (value.contains(',') || value.contains('"') || value.contains('\n')) {
      return '"${value.replaceAll('"', '""')}"';
    }
    return value;
  }
  
  Future<String> _saveFile(String fileName, String content) async {
    final directory = await getApplicationDocumentsDirectory();
    final file = File('${directory.path}/$fileName');
    await file.writeAsString(content);
    return file.path;
  }
}
